config/routes.rb
Rails.application.routes.draw do
  devise_for :installs
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'pages/home'
  get 'static_pages/portfolio'
  root 'pages#home'
  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,          :validate => true
  attribute :email,         :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,       :validate => true
  attribute :nickname,      :captcha => true

  def headers
    {
      :subject => "Graham Plata Dot Com Contact Form",
      :to => "graham.plata@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(2).order("created_at desc")
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def created
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if current_user
      redirect_to posts_path
    end  
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 3)
  end

  def new
    @post = Post.new
  end

  def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Your post was successfully saved!"
		else
			render 'new', notice: "Unable to save your post."
		end
	end

  def show
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to posts_path, notice: "Post was saved"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @projects = Project.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params

    if @project.save
      redirect_to @project, notice: "Project saved"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to @project, notice: "Project updated"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private
  def find_project
    @project = Project.friendly.find(params[:id])
  end
  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html:  true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/create.html.erb
<div>
  <br>
  <h6>Thanks for the message!</h6>
  <p>I'll get back to you soon.</p>
  <br>
</div>

app/views/contacts/new.html.erb
<div class="docs-section" id="contact">
  <div class="row">
    <div class="six columns">
      <h4>Contact</h4>
      <p>Want to work with me? Build something cool? Break something?</p>
    </div>
    <div class="six columns">
      <h4>Resume</h4>
      <p>Checkout my <%= link_to "resume", asset_path("GrahamPlata_resume.pdf") %></p>
    </div>
  </div>

  <hr>
  <div class="docs-example docs-example-forms">
    <div class="row">
        <div class="six columns">
          <%= form_for @contact do |f| %>
            <%= f.label :name %><br>
            <%= f.text_field :name, required: true, class: "u-full-width" %>
            <br>
        </div>
        <div class="six columns">
          <%= f.label :email %><br>
          <%= f.text_field :email, required: true, class: "u-full-width", placeholder: "name@company.com" %>
          <br>
        </div>
      </div>
      <div class="row">
      <%= f.label :message %><br>
      <%= f.text_area :message, required: true, placeholder: "Enter your rad idea!" %>
      <div class="hidden">
        <%= f.label :nickname %><br>
        <%= f.text_field :nickname, hint: "leave this blank" %>
      </div>
        <%= f.submit "Submit" %>
      <% end %>
    </div>
  </div>
</div>
<%= render 'partials/social' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Graham Plata</title>
  <meta name="description" content="">
  <meta name="author" content="Graham Plata">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="http://fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="images/png" href="images/favicon.png">
</head>
<body>
  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->

  <div class="container">
    <%= render 'partials/header' %>
    <%= render 'partials/navigation' %>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <!-- Footers -->
    <%= render 'partials/footer' %>
  </div>


</body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-11254643-2', 'auto');
  ga('send', 'pageview');

</script>
</html>

app/views/pages/home.html.erb
  <!-- Intro -->
  <%= render 'partials/intro' %>

app/views/partials/_blog.html.erb
<div class="docs-section" id="blog">
  <h4>Blog</h4>
  <h6>Taming my monkey mind one post at a time.</h6>
  <hr>

  <%= @posts.each do |post| %>
    <h6 class="docs-header"><%= link_to post.title, post %></h6>
    <hr>
    <p><%= post.created_at.strftime("%A, %b %d") %></p>
    <hr>
  <% end %>

</div>

app/views/partials/_contact.html.erb
<div class="docs-section" id="contact">
  <h4>Contact</h4>
  <p>Want to work with me? Build something cool? Break something? Lets push some boundries together!</p>
  <hr>
  
  <div class="docs-example docs-example-forms">
    <form>
      <div class="row">
        <div class="six columns">
          <label for="exampleEmailInput">Your email</label>
          <input class="u-full-width" type="email" placeholder="You@YourRadMailbox.com" id="exampleEmailInput">
        </div>
        <div class="six columns">
          <label for="exampleRecipientInput">Headline</label>
          <select class="u-full-width" id="exampleRecipientInput">
            <option value="Option 1">Questions</option>
            <option value="Option 2">Comments</option>
            <option value="Option 3">I am just a bot and I figured I you would like some spam.</option>
          </select>
        </div>
      </div>
      <label for="exampleMessage">Message</label>
      <textarea class="u-full-width" placeholder="Enter your rad idea &hellip;" id="exampleMessage"></textarea>
      <label class="example-send-yourself-copy">
        <input type="checkbox">
        <span class="label-body">Send a copy to yourself</span>
      </label>
      <input class="button-primary" type="submit" value="Submit">
    </form>
  </div>
</div>

app/views/partials/_footer.html.erb
<br>
<footer class="footer">
    <div class="row">
        <div class="six columns">
            <p style="float: left;">Built on rails. made with
                <i class="fa fa-heart-o" aria-hidden="true" style="color: red;"></i>
                by
                <a href="https://twitter.com/grahamplata">@grahamplata</a>
            </div>
            <div class="six columns">
                <% TwitterApi.our_public_tweets.each do |tweet| %>
                <p style="float: right;">
                    <i class="fa fa-twitter" aria-hidden="true" style="color: lightblue;"></i>
                    - "
                    <%= tweet.text %>
                    "</p>
                <% end %>
            </div>
        </div>
    </footer>

app/views/partials/_header.html.erb
<section class="header">
  <h2 class="title">Graham Plata</h2>
  <h6>Welcome to my digital sandbox.</h6>
</section>

app/views/partials/_intro.html.erb
<div class="docs-section" id="intro">
    <h4>Intro</h4>
    <h6>Hi, I'm Graham!</h6>
    <hr>
    <h6 class="docs-header">What am I known for?</h6>
    <p>I am known for my technological prowess and keen eye for design.</p>

    <h6 class="docs-header">Where am I Currently?</h6>
    <p>Right now I work as a private contractor for UnicaLabs in Philadelphia, PA.</p>

    <h6 class="docs-header">Best memory</h6>
    <p>My most memorable moment thus far was acting as Director of Photography for a collaboration project between BMW and Men's Health.</p>

    <hr>

    <div class="row">
        <div class="six columns">
            <h6 class="docs-header">Longer Biography</h6>
            <p>I am a filmmaker and amateur programmer based in Philadelphia, Pennsylvania. Currently I work as a private rails software developer alongside <a href="http://unicalabs.com/">UnicaLabs</a>. Prior to that I was with
                <a href="http://http://www.candoris.com/">Candoris</a>
                as a Client Warrior (Account Executive) specializing in enterprise data center sales. In 2013 I graduated from Temple University with a focus in new media. This allotted me the privilege to join up with the talented filmmakers at <a href="http://www.standardproduction.com/">Gabello Studios</a>. and <a href="http://www.shuffleboxproductions.com/">Shufflebox Productions</a>. </p>
        </div>
        <div class="six columns">
            <%= image_tag "4.PNG", :width => "100%", :alt => "Graham"  %>
        </div>

    </div>
</div>

app/views/partials/_navigation.html.erb
<nav class="navbar">
  <div class="container">
    <ul class="navbar-list">
      <li class="navbar-item"><a class="navbar-link" href="/">Intro</a></li>
      <li class="navbar-item"><a class="navbar-link" href="/posts">Blog</a></li>
      <li class="navbar-item"><a class="navbar-link" href="/projects">Projects</a></li>
      <li class="navbar-item"><a class="navbar-link" href="/static_pages/portfolio">Portfolio</a></li>
      <li class="navbar-item"><a class="navbar-link" href="/contacts/new">Contact</a></li>
    </ul>
  </div>
</nav>

app/views/partials/_portfolio.html.erb
<div class="docs-section" id="portfolio">
    <h4>Portfolio</h4>
    <h6>Checkout my reel.</h6>
    <hr>
  <div class="row">
    <div class="tweleve columns">
      <%= video_tag "showreel.mp4", :size => "900x480", :controls => true, :muted => true, :autoplay => true, :loop => true %>
      </div>
  </div>
</div>

app/views/partials/_projects.html.erb
<div class="docs-section" id="projects">
  <h4>Projects</h4>
  <h6>Checkout my recent work!</h6>
  <hr>
  <%= @projects.each do |project| %>
    <div class="row">
      <div class="six columns">

        <%= image_tag "1.PNG", :width => "100%"  %>
      </div>
      <div class="six columns">
        <h6 class="docs-header"><%= link_to project.title, project %></h6>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <%= link_to project.link %>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_social.html.erb
<nav class="navbar">
  <div class="container">
    <ul class="navbar-list">
      <li class="navbar-item"><a href="http://twitter.com/grahamplata"><i class="fa fa-twitter navbar-link" aria-hidden="true"></i></a></li>
      <li class="navbar-item"><a href="http://instagram.com/grahamplata"><i class="fa fa-instagram navbar-link" aria-hidden="true"></i></a></li>
      <li class="navbar-item"><a href="http://github.com/grahamplata"><i class="fa fa-github navbar-link" aria-hidden="true"></i></a></li>
      <li class="navbar-item"><a href="http://vimeo.com/grahamplata"><i class="fa fa-vimeo navbar-link" aria-hidden="true"></i></a></li>
      <li class="navbar-item"><a href="https://steamcommunity.com/id/grahamplata"><i class="fa fa-steam navbar-link" aria-hidden="true"></i></a></li>
    </ul>
  </div>
</nav>

app/views/partials/_specialnav.html.erb
<nav class="navbar">
  <div class="container">
    <ul class="navbar-list">
      <li class="navbar-item"><a class="navbar-link" href="/">Home</a></li>
      <li class="navbar-item"><a class="navbar-link" href="/posts">Posts</a></li>
      <li class="navbar-item"><a class="navbar-link" href="/posts/new">New</a></li>
    </ul>
  </div>
</nav>

app/views/partials/_specialnavthree.html.erb
<nav class="navbar">
  <div class="container">
    <ul class="navbar-list">
      <li class="navbar-item"><a class="navbar-link" href="/">Home</a></li>
      <li class="navbar-item"><a class="navbar-link" href="/contact">Contact</a></li>
    </ul>
  </div>
</nav>

app/views/partials/_specialnavtwo.html.erb
<nav class="navbar">
  <div class="container">
    <ul class="navbar-list">
      <li class="navbar-item"><a class="navbar-link" href="/">Home</a></li>
      <li class="navbar-item"><a class="navbar-link" href="/projects">Projects</a></li>
      <li class="navbar-item"><a class="navbar-link" href="/projects/new">New</a></li>
    </ul>
  </div>
</nav>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

  var disqus_shortname = 'grahamplata-com';
  var disqus_identifier = '<%= @post.id %>';
  var disqus_title = '<%= @post.title %>';
  var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';

(function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = '//grahamplata-com.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();
</script>

<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error")  %> prevented this post from saving:</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title, "Write title here" %><br>
  <%= f.text_field :title %>

  <%= f.label :content, "Write post here" %><br>
  <%= f.text_area :content %>
<%= f.submit %>
  <br>
  <br>
<% end %>

app/views/posts/edit.html.erb
<!-- Content -->
<br>
<h6 class="docs-header">Edit Post</h6>
<br>

<%= render 'form' %>
<!-- Footers -->

app/views/posts/index.html.erb
<div class="docs-section" id="blog">
    <h4>Blog</h4>
    <h6>I am still buidling out the backend of my website so I am currently lacking the blog functionality. Enjoy the hint of what is to come.</h6>

    <br>
    <% @posts.each do |post| %>

    <h4 class="docs-header u-pull-left"><%= link_to post.title, post %></h4>
    <p class="u-pull-right">
        <em><%= post.created_at.strftime("%A, %b %d") %></em>
    </p>
    <br>
    <br>
    <p><%= sanitize(post.content[0,420]) + "..." %></p>
    <% end %>
    <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<!-- Content -->
<br>
<h6 class="docs-header">New Post</h6>
<br>

<%= render 'form' %>

app/views/posts/show.html.erb
<!-- Content -->
<br>
<% if user_signed_in? %>
  <div class="admin_links">
    <%= link_to "Edit Post", edit_post_path(@post) %>
    <%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
<% end %>
<h4 class="docs-header"><%= @post.title %></h4> <br>
<br>
<div class="container">
<%= markdown @post.content %>
<br>
<hr>
</div>
<%= render 'posts/disqus' %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <h2><%= pluralize(@project.errors.count, "error")  %> prevented this post from saving:</h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title, "Write title here" %><br>
  <%= f.text_field :title %>

  <%= f.label :description %><br>
  <%= f.text_area :description %>

  <%= f.label :link %><br>
  <%= f.text_field :link %>
<%= f.submit %>
  <br>
  <br>
<% end %>

app/views/projects/edit.html.erb
<!-- Content -->
<br>
<h6 class="docs-header">Edit Project</h6>
<br>
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="docs-section" id="projects">
  <h4>Projects</h4>
  <h6>I am still buidling out the backend of my website so I am currently lacking the blog functionality. Enjoy the hint of what is to come.</h6>
    <br>
  <% @projects.each do |project| %>
    <h6 class="docs-header u-pull-left"><%= link_to project.title, project %></h6>
      <p class="u-pull-right"><em><%= project.created_at.strftime("%A, %b %d") %></em></p>
      <br>
      <br>
      <p><%= sanitize(project.description[0,420]) + "..." %></p>
      <hr>
  <% end %>
  <%= will_paginate @posts %>
</div>

app/views/projects/new.html.erb
<!-- Content -->
<br>
<h6 class="docs-header">New Project</h6>
<br>

<%= render 'form' %>

app/views/projects/show.html.erb
<br>
<h4 class="docs-header"><%= @project.title %></h4> <br>
<% if user_signed_in? %>
  <div class="admin_links">
    <%= link_to "Edit Post", edit_project_path(@project) %>
    <%= link_to "Delete Post", project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
<% end %>
<%= markdown @project.description %>
<br>
<br>

app/views/static_pages/portfolio.html.erb
<div class="docs-section" id="projects">
  <h4>Portfolio</h4>
  <h6>Checkout my reel.</h6>
    <hr>
  <div class="row">

      <%= video_tag "showreel.mp4", :size => "900x480", :controls => true, :muted => true, :autoplay => true, :loop => true %>

  </div>
</div>